
include:
  - path: ./rabbitmq/docker-compose.yaml
  - path: ./kong-konga/docker-compose.yaml
  
  - path: ../usersapi/docker-compose.yaml
    env_file: ../usersapi/.env.aws

  - path: ../catalogapi/docker-compose.yaml
    env_file: ../catalogapi/.env.aws

  - path: ../notificationsapi/docker-compose.yaml
    env_file: ../notificationsapi/.env.aws

  - path: ../paymentsapi/docker-compose.yaml
    env_file: ../paymentsapi/.env.aws

  - path: ./newrelic-infra/docker-compose.yaml
  

networks:
  microsservicos-net:
    name: app-network
    driver: bridge