
include:
  - path: ./rabbitmq/docker-compose.yaml
  - path: ./kong-konga/docker-compose.yaml
  
  - path:
      - ../usersapi/docker-compose.yaml
      - ../usersapi/docker-compose.local.yaml
    env_file: ../usersapi/.env.local

  - path:
      - ../catalogapi/docker-compose.yaml
      - ../catalogapi/docker-compose.local.yaml
    env_file: ../catalogapi/.env.local

  - path:
      - ../notificationsapi/docker-compose.yaml
      - ../notificationsapi/docker-compose.local.yaml
    env_file: ../notificationsapi/.env.local

  - path:
      - ../paymentsapi/docker-compose.yaml
      - ../paymentsapi/docker-compose.local.yaml
    env_file: ../paymentsapi/.env.local


  - path: ./newrelic-infra/docker-compose.yaml
  

networks:
  microsservicos-net:
    name: app-network
    driver: bridge